---
version: "3"
services:
  windows:
    image: ghcr.io/prmiguel/custom-windows-11:main
    container_name: windows11
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "120G"
    devices:
    - /dev/kvm
    cap_add:
    - NET_ADMIN
    ports:
    - 8006:8006
    - 3389:3389/tcp
    - 3389:3389/udp
    - "3322:22"
    stop_grace_period: 2m
    restart: on-failure
    volumes:
    - ./data:/storage
